### ISSUE TITLE
Supporting more OS

### ISSUE THREAD

**Issue by ghost** [eyeson-team/pogo#2]
Hi!

I managed to make pogo work on Ubuntu 21.10 but not on Ubuntu 20.04, most probably due to the constraint on the glibc version. Is there any plan to extend the support of this executor to a wider range of OS?

Best regards

**Comment by unused** [comment]
Can you give me some details what kind of problems you ran into? Did you use the pre-build binary from the release to run pogo?

There is not much against providing a variety of binaries for a release, yet I'll likely skip windows and mac as first ships with wsl that might be much easier to handle and second does not run podman smoothly afaik.

**Comment by ghost** [comment]
Here it is:
```
Running with gitlab-runner 14.10.0 (c6bb62f6)
  on Podman K52aCyyj
Preparing the "custom" executor 00:00
/root/bin/pogo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/bin/pogo)
/root/bin/pogo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /root/bin/pogo)
WARNING: Cleanup script failed: exit status 1
ERROR: Job failed: exit status 1
```

It seems that one must have the right version of GLIBC in order to run the pogo executable. Only a few OS have the right version of GLIBC out of the box.

**Comment by unused** [comment]
Thanks for the details, I'll have a look.

**Comment by opusonline** [comment]
Closed due to long inactivity.
Please open a new ticket if you have any more questions. Thanks!
